# Hough Lİne Dönüşümleri
<img src="teori.png">

In [20]:
import cv2
import numpy as np

#img = cv2.imread("resimler/3.1 h_line.png.png")
img = cv2.imread("resimler/santrac.jpeg")

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

edges = cv2.Canny(gray,100,150) #canny kenar bulma algoritması kullanılıyor

#cv2.HoughLines() #çok fazla cpu kullanıyor
# şekildeki boşlukların çizilmesi için maxlinegap ekliyoruz
lines = cv2.HoughLinesP(edges,1,np.pi/180,80,maxLineGap=200) # resim,ro ve teta değerleri,threshold değeri girildi (shift+tab) basarak içine girilecek argümaları görebilirsin
print(lines)

#lines içimde dört değer saklar bunlar x ve y nin başlangıç ve bitiş değerleri
for line in lines:
    x1,y1,x2,y2 =line[0]
    cv2.line(img,(x1,y1),(x2,y2),(0,255,0),2)
    
    

cv2.imshow("img",img)
cv2.imshow("edges",edges)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[[478  14 504 781]]

 [[726  10 766 768]]

 [[733  11 773 770]]

 [[102  21 770   9]]

 [[ 20 658 809 630]]

 [[ 18 753 814 726]]

 [[ 17  55 774  42]]

 [[ 17 470  17  26]]

 [[ 17 747 814 719]]

 [[ 52 312 790 299]]

 [[143  59 156 794]]

 [[ 51 144 779 131]]

 [[230  57 243 790]]

 [[398 782 818 767]]

 [[ 52 227 785 214]]

 [[ 24 799 630 777]]

 [[639  20 679 774]]

 [[562  12 589 778]]

 [[ 18 754 814 727]]

 [[395  48 413 557]]

 [[790 292 815 766]]

 [[ 51  61 774  48]]

 [[ 19 571 755 546]]

 [[ 56  23  69 798]]

 [[727  47 764 768]]

 [[ 23 798 758 772]]

 [[730  59 767 768]]

 [[394  48 420 782]]

 [[ 60 387  67 798]]

 [[ 51  62 774  49]]

 [[786 229 803 541]]

 [[ 53 396 405 389]]

 [[271 788 486 780]]

 [[311 476 756 461]]

 [[228  57 240 740]]

 [[ 55  23  68 798]]

 [[ 21 745 770 719]]

 [[322 393 792 377]]

 [[ 55 701  55 531]]

 [[ 52 318 737 295]]

 [[324 477 756 462]]

 [[ 51  60 701  49]]

 [[ 18 527  18 371]]

 [[ 51 207  51  23]]

 [[393  48 419 782]]

 [[776  73

## video üzerinde hough line dönüşümleri

In [4]:
import cv2
import numpy as np

cap = cv2.VideoCapture("resimler/4.2 line.mp4.mp4") # pc deki video adını belirttik.

# her bir kare sonsuz bir while döngüsü ile yakalayarak video oluşturuyoruz.
while True:
    ret,frame = cap.read() # cap.read() sağlıklı bi şekilde görüntü okuduğunda true değerleri göndererek ret hafızasında saklanır
    frame = cv2.resize(frame,(640,480))
    #video bittiğinde ret de sıfır dönecek ve sağlıklı bi şekide videodan çıkabileceğiz bunuda if komutu ile algıladık
    if ret==0:
        break
    hsv = cv2.cvtColor(frame,cv2.COLOR_BGR2HSV) #FRAME hsv ye çevrildi
    
    #Opencv temel işlemler bölümünde yaptığın TRACKBAR HSV uygulaması ile aralıkları bulabilirsin
    #sarı nesne takibi
    yellow_lower=np.array([18, 94, 140 ],np.uint8) 
    yellow_upper=np.array([48, 255, 255],np.uint8)
    
    mask = cv2.inRange(hsv,yellow_lower,yellow_upper)
    
    
    
    edges = cv2.Canny(mask,75,250) #canny kenar bulma algoritması kullanılıyor
    lines = cv2.HoughLinesP(edges,1,np.pi/180,50,maxLineGap=50) # resim,ro ve teta değerleri,threshold değeri girildi (shift+tab) basarak içine girilecek argümaları görebilirsin
    
    #lines içimde dört değer saklar bunlar x ve y nin başlangıç ve bitiş değerleri
    for line in lines:
        x1,y1,x2,y2 =line[0]
        cv2.line(frame,(x1,y1),(x2,y2),(0,255,0),2)
        
    
    cv2.imshow("Yellow Line",frame)
    cv2.imshow("edges",edges)
    #burada waitkey içine girlen sayı her bir karenin kaç milisaniye gösterileceğidir
    if cv2.waitKey(50) & 0xFF == ord("q"): #0xFF q'nun makine dilinde ki karşılığıdır
        break
cap.release() 
cv2.destroyAllWindows()

<img src="resimler/houghcircle.png">

In [30]:
import cv2
import numpy as np

img = cv2.imread("resimler/5.1 coins.jpg.jpg")
#img = cv2.imread("resimler/5.2 balls.jpg.jpg")

gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

blur = cv2.medianBlur(gray,5) #görüntedeki gürültüleri azaltmak için kullandık


circles = cv2.HoughCircles(blur,cv2.HOUGH_GRADIENT,1,img.shape[0]/4,param1=200,param2=10,minRadius=15,maxRadius=80) #çemberler arasındaki min. mesafe girilmeli
#genellikle resmin shape değerinin 64 de bölünmesi ile sağlıklı bi değer elde edilir
#değerlerle oynarak sağlıklı bi sonuç elde edilebilir

if circles is not None: # tuttuğu değerler boş değilse
    circles =np.uint16(np.around(circles)) #circles içindeki değerleri yuvarlayıp tekrar circlesa kaydediyoruz
    for i in circles[0,:]: #
        cv2.circle(img,(i[0],i[1]),i[2],(0,255,0),2)
        
        
cv2.imshow("img",img)
cv2.waitKey(0)
cv2.destroyAllWindows()
