In [2]:
import cv2
import numpy as np

## Yapacağımız çizimler için Tuval hazırladık

In [9]:
canvas = np.zeros((512,512,3),dtype=np.uint8) +255  #kendimize çizim yapabilmek için bir tuval hazırladık(+255-Beyaz tuval)
print(canvas)
cv2.imshow("Canvas",canvas) 
cv2.waitKey(0) #herhangi bir tuşa basınca pencere kapanır
cv2.destroyAllWindows()

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


### pikselleri tek tek renklendirme

In [8]:
img=np.zeros((10,10,3),np.uint8) #tuvalemizi belirledik

#pikselleri tek tek renklendiriyoruz
img[0,0]=(255,255,255)
img[0,1]=(200,255,200)
img[0,2]=(150,255,150)
img[0,3]=(15,255,15)



img= cv2.resize(img,(800,800),interpolation=cv2.INTER_AREA) #yeniden boyutlandırdık


cv2.imshow("Canvas",img) 
cv2.waitKey(0) #herhangi bir tuşa basınca pencere kapanır
cv2.destroyAllWindows()

## Çizgi , Kare ,Çember ,Üçgen Çizme

In [33]:
canvas = np.zeros((512,512,3),dtype=np.uint8) +255  #kendimize çizim yapabilmek için bir tuval hazırladık(+255-Beyaz tuval)

# çizgi çizme
cv2.line(canvas,(50,50),(512,512),(255,0,0),thickness=5) #  (başlangıç,bitiş,renk,kalınlık)
cv2.line(canvas,(100,50),(200,250),(0,0,250),thickness=3) #  (başlangıç,bitiş,renk,kalınlık)

# Kare Çizme
cv2.rectangle(canvas,(20,20),(50,50),(0,255,0),thickness=3) # (sol_üst_köşe,sağ_alt_köşe,renk,kalınlık)
cv2.rectangle(canvas,(300,300),(150,150),(0,255,0),thickness=-1) # eğer kalınlık değeri -1 verilirse içi dolu kare çizilir

# Çember Çizme
cv2.circle(canvas,(400,250),100,(0,0,255),thickness=-1) #(merkez nok,yarı çapı,renk,kalınlık)

#üçgen çizme
p1=(100,200)
p2=(50,50)
p3=(300,100)

cv2.line(canvas,p1,p2,(0,0,0),4)
cv2.line(canvas,p2,p3,(0,0,0),4)
cv2.line(canvas,p1,p3,(0,0,0),4)

#polylines ile çok kenarlı şekiller çizme
points = np.array([[[110,200],[300,220],[100,220],[80,80]]],np.int32)
cv2.polylines(canvas,[points],True,(0,0,100),5 )

#elips çizimi
cv2.ellipse(canvas,(300,300),(80,20),10,90,360,(255,255,0),-1) #(merkez noktası,(en,boy),yatay ile yaptığı açı,)


cv2.imshow("Canvas",canvas) 
cv2.waitKey(0) #herhangi bir tuşa basınca pencere kapanır
cv2.destroyAllWindows()

## Yazı yazdırma

In [43]:
canvas = np.zeros((512,512,3),dtype=np.uint8) +255  #kendimize çizim yapabilmek için bir tuval hazırladık(+255-Beyaz tuval)


#yazı fontları 
font1 = cv2.FONT_HERSHEY_SIMPLEX
font2 = cv2.FONT_HERSHEY_COMPLEX
font3 = cv2.FONT_HERSHEY_SCRIPT_COMPLEX


cv2.putText(canvas,'OpenCV',(30,100),font1,2,(0,0,0),cv2.LINE_4) #(çizilicek yer adı,yazılacak yazı,metnin konumu,FONT)

cv2.imshow("Canvas",canvas) 
cv2.waitKey(0) #herhangi bir tuşa basınca pencere kapanır
cv2.destroyAllWindows()

## Trackbar renk değerleri ile oynama

In [23]:
 def nothing(x):
        
        pass
    
img = np.zeros((600,512,3),dtype=np.uint8) #çizim ekranı oluşturuldu
cv2.namedWindow("image") # yeniden adlandırıldı

cv2.createTrackbar("R","image",0,255,nothing) # trackbara tuşlar ve görevler atandı
cv2.createTrackbar("G","image",0,255,nothing) # adı G ve değişim aralığı 0-255
cv2.createTrackbar("B","image",0,255,nothing)
switch='ON:1\nOFF'
cv2.createTrackbar(switch,"image",0,1,nothing)

while True:
    cv2.imshow("image",img)
    if cv2.waitKey(1) & 0xFF == ord("q"):
        break
    r = cv2.getTrackbarPos("R","image")
    g = cv2.getTrackbarPos("G","image")
    b = cv2.getTrackbarPos("B","image")
    s = cv2.getTrackbarPos(switch,"image")
    
    if s == 0:
         img[:] = [0,0,0]
    else:
        img[:] = [b, g, r]


cv2.destroyAllWindows()